Greatly optimised code
kami-blue/website-rewrite pull request #2
Opened 2020-09-15 04:47 UTC by sourTaste000

tl;dr deleted a lot of useless code

2020-09-15 04:48 UTC, sourTaste000 commented
also let css to do the 404 page, not an image.

2020-09-15 12:40 UTC, dominikaaaa requested changes

2020-09-15 12:40 UTC, dominikaaaa commented on 404.html
> -	<meta content="/assets/images/logoSmall.png" property="twitter:image">
we previously had these because they improve SEO

2020-09-15 12:40 UTC, dominikaaaa commented on assets/404/style.css
> +	font-family: "JetBrains Mono", "Fira Code Retina", Courier, monospace;
Fira Code Retina should be first

2020-09-15 14:40 UTC, humboldt123 commented
Please make the changes @dominikaaaa suggested.

2020-09-15 14:41 UTC, dominikaaaa commented
We should be using templates per each page. I'll make that change myself

2020-09-15 14:42 UTC, dominikaaaa commented on assets/404/style.css
> +	font-family: "JetBrains Mono", "Fira Code Retina", Courier, monospace;
Also I'm not sure if it'll work, looking at the original file. https://github.com/tonsky/FiraCode/issues/1126

2020-09-15 14:44 UTC, humboldt123 commented
Good idea.

2020-09-15 16:43 UTC, dominikaaaa requested changes

2020-09-15 16:43 UTC, dominikaaaa commented on assets/index/script.js
> +      <br>When making a pull request or issue, please follow the Code of Conduct
this is todo tho

2020-09-17 04:04 UTC, sourTaste000 commented
bruh conflict be like

2020-09-17 04:09 UTC, closed without merging

2020-09-17 11:55 UTC, humboldt123 commented
I recommend copying the files, manually committing, then making a pull.